output: 'lib/src/generated_bindings.dart'
headers:
  entry-points:
    - 'open62541/main.c'
enums:
  exclude:
    - "^_.*"
    - "^(?!UA_).*"

functions:
  exclude:
    - "^_.*"
    - "^(?!UA_).*"  # Corrected to provide the pattern directly as a string
structs:
  exclude:
    - "^_.*"
    - "^(?!UA_).*"
libraries:  # Corrected the typo
  exclude:
    - "^_.*"
variables:
  exclude:
    - "^_.*"
    - "^(?!UA_).*"
defines:
  exclude:
    - "^_.*"
    - "^(?!UA_).*"
# dart run ffigen --config config.yaml
